name: soft-ap
version: 0.1
config: usr/bin/config.py
vendor: Ricardo Mendoza <ricardo.mendoza@canonical.com>

services:
  dnsmasq:
    start: bin/dnsmasq.sh
    security-template: unconfined
  hostapd:
    start: bin/hostapd.sh
    security-template: unconfined
  heartbeat:
    start: bin/heartbeat.sh
    security-template: unconfined
  server:
    start: bin/softap.sh
    security-template: unconfined

summary: Configurable SoftAP for Ubuntu Core
description: Configurable SoftAP for Ubuntu Core
icon: icon.png
type: app

parts:
  softap-server:
    plugin: go
    source: softap/
    snap:
      - bin/
  softap-static:
    plugin: copy
    files:
        softap.sh: bin/softap.sh
        dnsmasq.sh: bin/dnsmasq.sh
        hostapd.sh: bin/hostapd.sh
        heartbeat.sh: bin/heartbeat.sh
        dnsmasq.conf: dnsmasq.conf
        hostapd.conf: hostapd.conf
        config.py: usr/bin/config.py
        static: static
    stage-packages:
      - dnsmasq
      - hostapd
      - curl
      - iw
      - wireless-tools
    snap:
      - static/
      - sbin/
      - bin/
      - lib/
      - usr/bin
      - usr/sbin
      - usr/lib
      - dnsmasq.conf
      - hostapd.conf
